<?php
require_once __DIR__ . '/../../src/bootstrap.php';

use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Shared\Date as ExcelDate;

header('Content-Type: application/json; charset=utf-8');

function parse_text_date(string $value): string
{
    $value = trim($value);
    foreach (['d/m/Y', 'd-m-Y', 'd/m/y', 'd-m-y', 'Y-m-d'] as $format) {
        $date = DateTime::createFromFormat($format, $value);
        if ($date !== false) {
            return $date->format('Y-m-d');
        }
    }
    $timestamp = strtotime($value);
    return $timestamp ? date('Y-m-d', $timestamp) : '';
}

function respond(array $payload): never
{
    echo json_encode($payload);
    exit;
}

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    respond(['success' => false, 'message' => 'Method not allowed']);
}

$file = $_FILES['excel_file'] ?? null;
if (!$file || $file['error'] !== UPLOAD_ERR_OK) {
    respond(['success' => false, 'message' => 'ບໍ່ພົບ file ຫຼືອັບໂຫລດລົ້ມເຫລວ']);
}

$extension = strtolower(pathinfo($file['name'], PATHINFO_EXTENSION));
if (!in_array($extension, ['xlsx', 'xls'], true)) {
    respond(['success' => false, 'message' => 'ຮອງຮັບສະເພາະ file .xlsx ຫຼື .xls']);
}

// Turn PHP warnings/notices during parsing (e.g. a malformed cell) into catchable
// exceptions instead of letting them print HTML into the JSON response body.
set_error_handler(function ($severity, $message, $file, $line) {
    throw new ErrorException($message, 0, $severity, $file, $line);
});

try {
    $spreadsheet = IOFactory::load($file['tmp_name']);

    // Prefer the sheet generated by our own template (see delivery_template.php) —
    // uploaded workbooks often carry extra sheets (e.g. the source SAP export), and
    // getActiveSheet() only reflects whichever tab happened to be focused when the
    // user last saved the file, which is not reliably the "Delivery Detail" one.
    $sheet = $spreadsheet->sheetNameExists('Delivery Detail')
        ? $spreadsheet->getSheetByName('Delivery Detail')
        : $spreadsheet->getActiveSheet();

    $rows = [];

    foreach ($sheet->getRowIterator(2) as $row) {
        // Read each cell's value immediately while the iterator is on it — a Cell
        // object collected into an array and read later throws "Coordinate no
        // longer exists" once the iterator moves on, for blank cells in particular.
        $values = [];
        $cellIterator = $row->getCellIterator('A', 'F');
        $cellIterator->setIterateOnlyExistingCells(false);
        foreach ($cellIterator as $cell) {
            $values[] = $cell->getCalculatedValue();
        }

        [$dateValue, $soValue, $litersValue, $noteValue, $arValue, $taxValue] = $values;

        $deliveryDate = '';
        if ($dateValue !== null && $dateValue !== '') {
            // Excel always stores dates as a numeric day-count internally, even when the
            // cell wasn't styled with a date number format (e.g. pasted as plain numbers) —
            // so treat any numeric value here as a date serial rather than trusting isDateTime().
            if (is_numeric($dateValue)) {
                try {
                    $deliveryDate = ExcelDate::excelToDateTimeObject((float) $dateValue)->format('Y-m-d');
                } catch (Throwable $e) {
                    $deliveryDate = '';
                }
            } else {
                $deliveryDate = parse_text_date((string) $dateValue);
            }
        }

        $salesOrderNo = trim((string) $soValue);
        $liters = trim((string) $litersValue);
        $deliveryNoteNo = trim((string) $noteValue);
        $arInvoiceNo = trim((string) $arValue);
        $taxNo = trim((string) $taxValue);

        if ($deliveryDate === '' && $salesOrderNo === '' && $liters === '' && $deliveryNoteNo === '' && $arInvoiceNo === '' && $taxNo === '') {
            continue;
        }

        $rows[] = [
            'delivery_date' => $deliveryDate,
            'sales_order_no' => $salesOrderNo,
            'liters' => $liters !== '' ? (string) (float) $liters : '',
            'delivery_note_no' => $deliveryNoteNo,
            'ar_invoice_no' => $arInvoiceNo,
            'tax_no' => $taxNo,
        ];
    }
} catch (Throwable $e) {
    restore_error_handler();
    respond(['success' => false, 'message' => 'ອ່ານ file ບໍ່ໄດ້: ' . $e->getMessage()]);
}

restore_error_handler();
respond(['success' => true, 'rows' => $rows]);
